# Generated by Django 4.2.7 on 2023-11-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='img',
            field=models.ImageField(default='images', upload_to='images'),
            preserve_default=False,
        ),
    ]
